DOMAIN = "hatg"
NAME = "HATG"
VERSION = "0.2.11"

PANEL_URL = "hatg"
PANEL_TITLE = "HATG"
PANEL_ICON = "mdi:palette-swatch"
PANEL_TAG = "hatg-panel"
STATIC_PATH = "/hatg_static"
FRONTEND_MODULE = "/hatg_static/hatg-panel.js?v=0.2.11"
